name: Hexo Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    strategy:
        matrix:
          node-version: [18.20.0]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
  
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "雨霖铃"
          git config --global user.email "rsgltzyd@hotmail.com"
          npm install hexo-cli -g
          npm install
          echo 'Environment deploy successful!'

      - name: Deploy
        run: |
          hexo clean
          hexo deploy
          echo 'deploy successful!'